### ISSUE TITLE
Hey, Bitte Fix das

### ISSUE THREAD

**Issue by SGirl-Zockt** [Monstanner/DuckDuckGo-Fakeshops-Blocklist#3]
[i] Target: https://raw.githubusercontent.com/Monstanner/DuckDuckGo-Fakeshops-Blocklist/main/Blockliste
  [✓] Status: Retrieval successful
  [✓] Parsed 912 exact domains and 0 ABP-style domains (ignored 1 non-domain entries)
      Sample of non-domain entries:
        - "zzib.d"

**Comment by Monstanner** [comment]
Danke für den Hinweis. Wurde jetzt behoben.
